query EventSync($slug: String!, $page: Int!, $perPage: Int!) {
  event(slug: $slug) {
    id
    name
    tournament {
      id
      name
      slug
    }
    phases {
      id
      name
      phaseOrder
    }
    phaseGroups {
      id
      bracketType
      displayIdentifier
      sets(page: 1, perPage: 200, sortType: STANDARD) {
        nodes {
          id
        }
      }
      tiebreakOrder
      progressionsOut {
        id
        originOrder
        originPhase {
          id
          name
          phaseOrder
        }
        originPhaseGroup {
          id
          displayIdentifier
          phase {
            id
            name
            phaseOrder
          }
        }
        originPlacement
        placeholderName
      }
        seedMap
      phase {
        id
        name
        phaseOrder
      }
      seeds(query: { page: 1, perPage: 200 }) {
        nodes {
            id
          groupSeedNum
            seedNum
            placement
            placeholderName
            progressionSource {
              id
              originOrder
              originPhase {
                phaseOrder
              }
              originPhaseGroup {
                id
                displayIdentifier
              }
              originPlacement
            }
            entrant {
              id
              name
            }
        }
      }
    }
    sets(page: $page, perPage: $perPage, sortType: STANDARD) {
      nodes {
        id
        identifier
        fullRoundText
        round
        phaseGroup {
          id
          displayIdentifier
          phase {
            name
            phaseOrder
          }
        }
        state
        winnerId
      }
    }
  }
}
