schema {
  query: Query
  mutation: Mutation
}

scalar ID
scalar GgID
scalar JSON

type Query {
  tournament(slug: String!): Tournament
  set(id: ID!): Set
  seed(id: ID): Seed
  event(slug: String!): Event
  currentUser: User
  tournaments(query: TournamentPaginationQuery): TournamentConnection
}

type Mutation {
  reportBracketSet(setId: ID!, winnerId: ID!, gameData: [BracketSetGameDataInput]): [Set]
  resetSet(setId: ID!, resetDependentSets: Boolean): Set
}

input BracketSetGameDataInput {
  winnerId: ID
  gameNum: Int
}

type Tournament {
  id: GgID!
  name: String
  slug: String
  events: [Event]
}

type User {
  id: GgID!
}

type TournamentConnection {
  nodes: [Tournament]
}

input TournamentPaginationQuery {
  perPage: Int
  page: Int
  filter: TournamentQueryFilter
}

input TournamentQueryFilter {
  ownerId: ID
}

type Event {
  id: GgID!
  name: String
  slug: String
  tournament: Tournament
  phases: [Phase]
  phaseGroups: [PhaseGroup]
  sets(page: Int, perPage: Int, sortType: SetSortType): SetConnection
}

type SetConnection {
  nodes: [Set]
}

type Set {
  id: GgID!
  identifier: String
  fullRoundText: String
  round: Int
  phaseGroup: PhaseGroup
  state: Int
  winnerId: GgID
  wPlacement: Int
  lPlacement: Int
  entrant1Source: SetEntrantSource
  entrant2Source: SetEntrantSource
  winnerProgressionSeed: Seed
  loserProgressionSeed: Seed
  slots: [SetSlot]
}

type SetEntrantSource {
  type: String!
  typeId: GgID
  condition: String
  conditionString: String
}

type PhaseGroup {
  id: GgID!
  bracketType: BracketType
  displayIdentifier: String
  phase: Phase
  progressionsOut: [Progression]
  seedMap: JSON
  seeds(query: SeedPaginationQuery!, eventId: ID): SeedConnection
}

input SeedPaginationQuery {
  page: Int
  perPage: Int
}

type SeedConnection {
  nodes: [Seed]
}

enum BracketType {
  SINGLE_ELIMINATION
  DOUBLE_ELIMINATION
  ROUND_ROBIN
  SWISS
  EXHIBITION
  CUSTOM_SCHEDULE
  MATCHMAKING
  ELIMINATION_ROUNDS
  RACE
  CIRCUIT
}

type Phase {
  id: GgID!
  name: String
  phaseOrder: Int
}

type SetSlot {
  entrant: Entrant
  seed: Seed
  standing: Standing
}

type Seed {
  id: GgID!
  entrant: Entrant
  groupSeedNum: Int
  seedNum: Int
  placeholderName: String
  placement: Int
  progressionSource: Progression
}

type Progression {
  id: GgID!
  originOrder: Int
  originPhase: Phase
  originPhaseGroup: PhaseGroup
  originPlacement: Int
  placeholderName: String
}

type Entrant {
  id: GgID!
  name: String
}

type Standing {
  stats: StandingStats
}

type StandingStats {
  score: Score
}

type Score {
  value: Float
}

enum SetSortType {
  STANDARD
}
