query SetSnapshotDetail($setId: ID!) {
  set(id: $setId) {
    id
    identifier
    fullRoundText
    round
    phaseGroup {
      displayIdentifier
      phase {
        name
        phaseOrder
      }
    }
    state
    winnerId
    entrant1Source {
      type
      typeId
      condition
      conditionString
    }
    entrant2Source {
      type
      typeId
      condition
      conditionString
    }
    winnerProgressionSeed {
      id
      seedNum
      placeholderName
      progressionSource {
        originOrder
        originPhase {
          id
          name
          phaseOrder
        }
        originPhaseGroup {
          id
          displayIdentifier
          phase {
            id
            name
            phaseOrder
          }
        }
        originPlacement
        placeholderName
      }
    }
    loserProgressionSeed {
      id
      seedNum
      placeholderName
      progressionSource {
        originOrder
        originPhase {
          id
          name
          phaseOrder
        }
        originPhaseGroup {
          id
          displayIdentifier
          phase {
            id
            name
            phaseOrder
          }
        }
        originPlacement
        placeholderName
      }
    }
    slots {
      seed {
        id
        seedNum
        placeholderName
        progressionSource {
          originOrder
          originPhase {
            id
            name
            phaseOrder
          }
          originPhaseGroup {
            id
            displayIdentifier
            phase {
              id
              name
              phaseOrder
            }
          }
          originPlacement
          placeholderName
        }
      }
      entrant {
        id
        name
      }
      standing {
        stats {
          score {
            value
          }
        }
      }
    }
  }
}
