query SetSnapshotDetail($setId: ID!) {
  set(id: $setId) {
    id
    fullRoundText
    round
    phaseGroup {
      displayIdentifier
      phase {
        name
      }
    }
    state
    winnerId
    entrant1Source {
      typeId
      condition
      conditionString
    }
    entrant2Source {
      typeId
      condition
      conditionString
    }
    winnerProgressionSeed {
      id
      seedNum
    }
    loserProgressionSeed {
      id
      seedNum
    }
    slots {
      seed {
        id
        seedNum
      }
      entrant {
        id
        name
      }
      standing {
        stats {
          score {
            value
          }
        }
      }
    }
  }
}
