query TournamentSync($slug: String!, $perPage: Int!) {
  tournament(slug: $slug) {
    id
    name
    slug
    events {
      id
      name
      phaseGroups {
        id
        bracketType
        displayIdentifier
        progressionsOut {
          id
          originOrder
          originPhase {
            id
            name
            phaseOrder
          }
          originPhaseGroup {
            id
            displayIdentifier
            phase {
              id
              name
              phaseOrder
            }
          }
          originPlacement
          placeholderName
        }
        phase {
          id
          name
          phaseOrder
        }
        seeds(query: { page: 1, perPage: 200 }) {
          nodes {
            id
            seedNum
            placement
            placeholderName
            progressionSource {
              id
              originOrder
              originPhase {
                phaseOrder
              }
              originPhaseGroup {
                displayIdentifier
              }
              originPlacement
            }
            entrant {
              id
              name
            }
          }
        }
      }
      sets(page: 1, perPage: $perPage, sortType: STANDARD) {
        nodes {
          id
          identifier
          fullRoundText
          round
          phaseGroup {
            displayIdentifier
            phase {
              name
              phaseOrder
            }
          }
          state
          winnerId
          wPlacement
          lPlacement
          entrant1Source {
            type
            typeId
            condition
            conditionString
          }
          entrant2Source {
            type
            typeId
            condition
            conditionString
          }
          winnerProgressionSeed {
            id
            seedNum
            placeholderName
            progressionSource {
              id
              originOrder
              originPhase {
                id
                name
                phaseOrder
              }
              originPhaseGroup {
                id
                displayIdentifier
                phase {
                  id
                  name
                  phaseOrder
                }
              }
              originPlacement
              placeholderName
            }
          }
          loserProgressionSeed {
            id
            seedNum
            placeholderName
            progressionSource {
              id
              originOrder
              originPhase {
                id
                name
                phaseOrder
              }
              originPhaseGroup {
                id
                displayIdentifier
                phase {
                  id
                  name
                  phaseOrder
                }
              }
              originPlacement
              placeholderName
            }
          }
          slots {
            seed {
              id
              seedNum
              placeholderName
              progressionSource {
                originOrder
                originPhase {
                  id
                  name
                  phaseOrder
                }
                originPhaseGroup {
                  id
                  displayIdentifier
                  phase {
                    id
                    name
                    phaseOrder
                  }
                }
                originPlacement
                placeholderName
              }
            }
            entrant {
              id
              name
            }
            standing {
              stats {
                score {
                  value
                }
              }
            }
          }
        }
      }
    }
  }
}
